import js from '@eslint/js';
import globals from 'globals';

const luciGlobals = {
  E: 'readonly',
  L: 'readonly',
  _: 'readonly',
  Request: 'readonly',
  administratorEditor: 'readonly',
  administratorModel: 'readonly',
  administratorView: 'readonly',
  backupModel: 'readonly',
  baseclass: 'readonly',
  commandActionsModel: 'readonly',
  deviceAccessLists: 'readonly',
  deviceEditor: 'readonly',
  deviceInventory: 'readonly',
  deviceSelection: 'readonly',
  deviceTableModel: 'readonly',
  deviceTypes: 'readonly',
  deviceTypeControlModel: 'readonly',
  detectionToolsModel: 'readonly',
  downloads: 'readonly',
  emergencySiteModel: 'readonly',
  feedbackPanel: 'readonly',
  form: 'readonly',
  fs: 'readonly',
  groupEditor: 'readonly',
  groupModel: 'readonly',
  groupPersistenceModel: 'readonly',
  groupView: 'readonly',
  integrationPanel: 'readonly',
  logModel: 'readonly',
  logPanelModel: 'readonly',
  navigationState: 'readonly',
  messengerSettings: 'readonly',
  notificationSettings: 'readonly',
  overview: 'readonly',
  pairingQr: 'readonly',
  routerBackend: 'readonly',
  routerInfo: 'readonly',
  routerDiscovery: 'readonly',
  routerMaintenance: 'readonly',
  scheduleEditor: 'readonly',
  scheduleModel: 'readonly',
  schedulePersistenceModel: 'readonly',
  scheduleView: 'readonly',
  secureOverview: 'readonly',
  secureRandom: 'readonly',
  settingsBackupModel: 'readonly',
  settingsBackupPanelModel: 'readonly',
  settingsDraftModel: 'readonly',
  settingsFieldsModel: 'readonly',
  settingsGeneralModel: 'readonly',
  settingsStorageModel: 'readonly',
  settingsMiscModel: 'readonly',
  settingsAiModel: 'readonly',
  settingsPersistenceModel: 'readonly',
  settingsSideEffectsModel: 'readonly',
  settingsTimeModel: 'readonly',
  sharedForms: 'readonly',
  sharedIcons: 'readonly',
  sheepfoldI18n: 'readonly',
  siteListStatus: 'readonly',
  storagePanelModel: 'readonly',
  uci: 'readonly',
  ui: 'readonly',
  view: 'readonly',
  wifiCards: 'readonly',
  wifiEditorModel: 'readonly',
  wifiPayload: 'readonly',
  wifiPersistenceModel: 'readonly',
  uciPersistenceModel: 'readonly',
  pairingPersistenceModel: 'readonly',
  devicePersistenceModel: 'readonly',
  backupPersistenceModel: 'readonly',
  administratorControllerModel: 'readonly',
  deviceControllerModel: 'readonly',
  emergencyPanelModel: 'readonly',
  groupControllerModel: 'readonly',
  groupNamingModel: 'readonly',
  navigationStateModel: 'readonly',
  overviewApplication: 'readonly',
  overviewEnvironmentModel: 'readonly',
  overviewStoreModel: 'readonly',
  pageRefreshModel: 'readonly',
  pageShellModel: 'readonly',
  quickAllowlistModel: 'readonly',
  scheduleControllerModel: 'readonly',
  settingsBackupControllerModel: 'readonly',
  settingsControllerModel: 'readonly',
  settingsSaveFlowModel: 'readonly',
  wifiControllerModel: 'readonly',
  rpc: 'readonly',
};

const commonRules = {
  ...js.configs.recommended.rules,
  'no-unused-vars': ['error', {
    args: 'none',
    caughtErrors: 'none',
    varsIgnorePattern: '^_$',
  }],
};

export default [
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    ignores: [
      '**/build/**',
      '**/dist/**',
      '**/node_modules/**',
      '.build/**',
      'tools/.cache/**',
      'tools/local/**',
    ],
  },
  {
    files: [
      'package/luci-app-sheepfold-family-internet-control/htdocs/luci-static/resources/**/*.js',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      parserOptions: {
        // LuCI выполняет ресурс внутри своей функции-модуля, поэтому return в файле допустим.
        ecmaFeatures: {
          globalReturn: true,
        },
      },
      globals: {
        ...globals.browser,
        ...luciGlobals,
      },
    },
    rules: commonRules,
  },
  {
    files: [
      'eslint.config.js',
      'scripts/**/*.mjs',
      'tests/**/*.mjs',
      'tools/**/*.mjs',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: globals.node,
    },
    rules: commonRules,
  },
  {
    files: ['tools/router-testing/frontendAudit.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
  },
];
