/*
 * Каноническая карта проблемных областей к test-файлам для выборочных прогонов.
 * Карта не выполняет тесты и не доказывает покрытие поведения; её полноту по именам
 * отдельно защищает testCategories.test.mjs.
 */
export const categoryDescriptions = Object.freeze({
  smoke: 'Быстрые межсистемные проверки без долгих сетевых стендов и сборки IPK.',
  luci: 'LuCI, переводы, вкладки, формы, модели и пользовательские действия.',
  access: 'Правила доступа, расписания, группы, администраторы и временные разрешения.',
  devices: 'Обнаружение, идентификация, присутствие, типы и привязка устройств.',
  sites: 'Списки сайтов, аварийно-полезные сайты, DNS, nftables и AdGuard Home.',
  backend: 'Router backend, API, UCI, сервисы, импорт и системные действия.',
  backendFast: 'Быстрые backend-контракты без долгих HTTP/DNS/firewall-стендов и сборки IPK.',
  policySimulation: 'Долгие shell-симуляции классификатора устройств и вычислителя расписаний.',
  networkIntegration: 'Долгие интеграционные стенды AdGuard Home, DNS, nftables и внешних списков.',
  android: 'Контракты родительского и детского Android-приложений.',
  security: 'Аутентификация, границы доступа, TLS, лимиты, секреты и безопасные обновления.',
  messaging: 'Telegram, запросы ребёнка и команды, приходящие через мессенджер.',
  ai: 'Граница Standard/AI Support, провайдеры и видимость AI-функций.',
  packaging: 'IPK, варианты продукта, локализация пакета, версия и обновление.',
  tooling: 'Инструменты репозитория, Windows-окружение и целостность тестовой карты.',
});

export const testCategories = Object.freeze({
  smoke: [
    'aiProviderSettings.test.mjs',
    'allowlistUi.test.mjs',
    'androidHttpsSecurity.test.mjs',
    'androidPairingDiscoveryAndListUi.test.mjs',
    'apiRateLimit.test.mjs',
    'backendRuntimeSafety.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'countryProfiles.test.mjs',
    'defaultGroups.test.mjs',
    'deprecationGuards.test.mjs',
    'deviceDetectionService.test.mjs',
    'deviceEvidenceHistory.test.mjs',
    'deviceDiscoverySecurity.test.mjs',
    'deviceDetectionUi.test.mjs',
    'deviceIdentityLinking.test.mjs',
    'deviceEditorUi.test.mjs',
    'devicePresence.test.mjs',
    'deviceStableId.test.mjs',
    'deviceTempAccessUi.test.mjs',
    'feedbackChannel.test.mjs',
    'frontendDomainModels.test.mjs',
    'frontendModules.test.mjs',
    'administratorEditorUi.test.mjs',
    'groupEditorUi.test.mjs',
    'logPanelUi.test.mjs',
    'logStorage.test.mjs',
    'liveRouterHarness.test.mjs',
    'lockCommon.test.mjs',
    'luciAssetVersioning.test.mjs',
    'overviewLocalization.test.mjs',
    'overviewSecureView.test.mjs',
    'overviewUi148.test.mjs',
    'openWrtBuildWorkflow.test.mjs',
    'packageManagerAdapter.test.mjs',
    'pairingDiagnostics.test.mjs',
    'pairingQrCapacity.test.mjs',
    'personalGroupWatermark.test.mjs',
    'rootPasswordGate.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'routerInfo.test.mjs',
    'routerIpv6.test.mjs',
    'settingsBackup.test.mjs',
    'settingsSecondLevelTabs.test.mjs',
    'simChangeMonitoring.test.mjs',
    'telegramCommandsSync.test.mjs',
    'telegramConfirmation.test.mjs',
    'tokenDeviceBinding.test.mjs',
    'windowsToolchain.test.mjs',
    'testCategories.test.mjs',
  ],
  luci: [
    'allowlistUi.test.mjs',
    'androidPairingDiscoveryAndListUi.test.mjs',
    'deviceDetectionUi.test.mjs',
    'deviceEditorUi.test.mjs',
    'devicePresence.test.mjs',
    'deviceTempAccessUi.test.mjs',
    'emergencySites.test.mjs',
    'feedbackChannel.test.mjs',
    'frontendDomainModels.test.mjs',
    'frontendModules.test.mjs',
    'administratorEditorUi.test.mjs',
    'groupEditorUi.test.mjs',
    'logPanelUi.test.mjs',
    'logStorage.test.mjs',
    'luciAssetVersioning.test.mjs',
    'overviewLocalization.test.mjs',
    'overviewSecureView.test.mjs',
    'overviewUi148.test.mjs',
    'pairingQrCapacity.test.mjs',
    'personalGroupWatermark.test.mjs',
    'rootPasswordGate.test.mjs',
    'routerInfo.test.mjs',
    'routerIpv6.test.mjs',
    'schedulePriorityUi.test.mjs',
    'settingsBackup.test.mjs',
    'settingsSecondLevelTabs.test.mjs',
    'simChangeMonitoring.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'countryProfiles.test.mjs',
  ],
  access: [
    'allowlistUi.test.mjs',
    'androidPairingDiscoveryAndListUi.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'defaultGroups.test.mjs',
    'deviceStableId.test.mjs',
    'deviceEditorUi.test.mjs',
    'deviceTempAccessUi.test.mjs',
    'firewallIntegration.test.mjs',
    'frontendDomainModels.test.mjs',
    'administratorEditorUi.test.mjs',
    'groupEditorUi.test.mjs',
    'personalGroupWatermark.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'schedulePriorityUi.test.mjs',
    'simChangeMonitoring.test.mjs',
    'tokenDeviceBinding.test.mjs',
  ],
  devices: [
    'allowlistUi.test.mjs',
    'androidPairingDiscoveryAndListUi.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'defaultGroups.test.mjs',
    'deviceDetectionService.test.mjs',
    'deviceDiscoverySecurity.test.mjs',
    'deviceDetectionUi.test.mjs',
    'deviceEditorUi.test.mjs',
    'deviceDetectorSafety.test.mjs',
    'deviceEvidenceHistory.test.mjs',
    'deviceFingerprintFixtures.test.mjs',
    'deviceIdentityLinking.test.mjs',
    'devicePassportDocumentation.test.mjs',
    'lockCommon.test.mjs',
    'devicePresence.test.mjs',
    'deviceStableId.test.mjs',
    'deviceTempAccessUi.test.mjs',
    'frontendDomainModels.test.mjs',
    'administratorEditorUi.test.mjs',
    'personalGroupWatermark.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'simChangeMonitoring.test.mjs',
    'tokenDeviceBinding.test.mjs',
  ],
  sites: [
    'adguardIntegration.test.mjs',
    'countryProfiles.test.mjs',
    'domainPolicyRuntime.test.mjs',
    'emergencySites.test.mjs',
    'firewallDomainPolicyRuntime.test.mjs',
    'firewallIntegration.test.mjs',
    'siteListResilience.test.mjs',
  ],
  backend: [
    'adguardIntegration.test.mjs',
    'apiRateLimit.test.mjs',
    'backendRuntimeSafety.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'countryProfiles.test.mjs',
    'defaultGroups.test.mjs',
    'deprecationGuards.test.mjs',
    'deviceDetectionService.test.mjs',
    'deviceDiscoverySecurity.test.mjs',
    'deviceDetectorSafety.test.mjs',
    'deviceEvidenceHistory.test.mjs',
    'deviceIdentityLinking.test.mjs',
    'deviceStableId.test.mjs',
    'domainPolicyRuntime.test.mjs',
    'emergencySites.test.mjs',
    'feedbackChannel.test.mjs',
    'firewallDomainPolicyRuntime.test.mjs',
    'firewallIntegration.test.mjs',
    'installLanguage.test.mjs',
    'logStorage.test.mjs',
    'lockCommon.test.mjs',
    'packageManagerAdapter.test.mjs',
    'pairingDiagnostics.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'routerInfo.test.mjs',
    'routerIpv6.test.mjs',
    'schedulePriorityUi.test.mjs',
    'settingsBackup.test.mjs',
    'simChangeMonitoring.test.mjs',
    'siteListResilience.test.mjs',
    'telegramCommandsSync.test.mjs',
    'telegramConfirmation.test.mjs',
    'tokenDeviceBinding.test.mjs',
    'updateTransportSafety.test.mjs',
  ],
  backendFast: [
    'apiRateLimit.test.mjs',
    'backendRuntimeSafety.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'countryProfiles.test.mjs',
    'defaultGroups.test.mjs',
    'deprecationGuards.test.mjs',
    'deviceDetectionService.test.mjs',
    'deviceDiscoverySecurity.test.mjs',
    'deviceEvidenceHistory.test.mjs',
    'deviceIdentityLinking.test.mjs',
    'deviceStableId.test.mjs',
    'emergencySites.test.mjs',
    'feedbackChannel.test.mjs',
    'installLanguage.test.mjs',
    'logStorage.test.mjs',
    'lockCommon.test.mjs',
    'pairingDiagnostics.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'routerInfo.test.mjs',
    'routerIpv6.test.mjs',
    'settingsBackup.test.mjs',
    'simChangeMonitoring.test.mjs',
    'telegramCommandsSync.test.mjs',
    'telegramConfirmation.test.mjs',
    'tokenDeviceBinding.test.mjs',
  ],
  policySimulation: [
    'deviceDetectorSafety.test.mjs',
    'deviceFingerprintFixtures.test.mjs',
    'schedulePriorityUi.test.mjs',
  ],
  networkIntegration: [
    'adguardIntegration.test.mjs',
    'domainPolicyRuntime.test.mjs',
    'firewallDomainPolicyRuntime.test.mjs',
    'firewallIntegration.test.mjs',
    'siteListResilience.test.mjs',
  ],
  android: [
    'androidHttpsSecurity.test.mjs',
    'androidPairingDiscoveryAndListUi.test.mjs',
    'childAccessRequest.test.mjs',
    'childAccessStatusTime.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'feedbackChannel.test.mjs',
    'pairingQrCapacity.test.mjs',
    'simChangeMonitoring.test.mjs',
    'tokenDeviceBinding.test.mjs',
  ],
  security: [
    'adguardIntegration.test.mjs',
    'administratorEditorUi.test.mjs',
    'androidHttpsSecurity.test.mjs',
    'apiRateLimit.test.mjs',
    'backendRuntimeSafety.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'deprecationGuards.test.mjs',
    'deviceDiscoverySecurity.test.mjs',
    'feedbackChannel.test.mjs',
    'firewallIntegration.test.mjs',
    'liveRouterHarness.test.mjs',
    'lockCommon.test.mjs',
    'pairingDiagnostics.test.mjs',
    'pairingQrCapacity.test.mjs',
    'rootPasswordGate.test.mjs',
    'routerBackendAccessRules.test.mjs',
    'routerIpv6.test.mjs',
    'simChangeMonitoring.test.mjs',
    'settingsBackup.test.mjs',
    'telegramConfirmation.test.mjs',
    'tokenDeviceBinding.test.mjs',
    'updateTransportSafety.test.mjs',
  ],
  messaging: [
    'childAccessRequest.test.mjs',
    'childWifiNetworkMonitoring.test.mjs',
    'deviceTempAccessUi.test.mjs',
    'simChangeMonitoring.test.mjs',
    'telegramCommandsSync.test.mjs',
    'telegramConfirmation.test.mjs',
  ],
  ai: [
    'aiProviderSettings.test.mjs',
    'settingsSecondLevelTabs.test.mjs',
  ],
  packaging: [
    'deprecationGuards.test.mjs',
    'installLanguage.test.mjs',
    'liveRouterHarness.test.mjs',
    'luciAssetVersioning.test.mjs',
    'overviewLocalization.test.mjs',
    'openWrtBuildWorkflow.test.mjs',
    'openWrtVariantFeed.test.mjs',
    'packageManagerAdapter.test.mjs',
    'productVariants.test.mjs',
    'testIpkI18n.test.mjs',
    'testIpkPermissions.test.mjs',
    'updateTransportSafety.test.mjs',
  ],
  tooling: [
    'frontendModules.test.mjs',
    'liveRouterHarness.test.mjs',
    'luciAssetVersioning.test.mjs',
    'overviewLocalization.test.mjs',
    'openWrtBuildWorkflow.test.mjs',
    'openWrtVariantFeed.test.mjs',
    'productVariants.test.mjs',
    'testCategories.test.mjs',
    'testIpkI18n.test.mjs',
    'testIpkPermissions.test.mjs',
    'windowsToolchain.test.mjs',
  ],
});
