/*
 * Защищает модульные границы большого LuCI view и отсутствие возврата логики в
 * overview.js. Тест читает только исходники; он не доказывает, что LuCI loader и
 * браузер успешно загрузят модули, поэтому дополнительно нужен frontend smoke.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const resources = join(root, 'package/luci-app-sheepfold-family-internet-control/htdocs/luci-static/resources');
const overview = readFileSync(join(resources, 'view/sheepfold/overview.js'), 'utf8');

function moduleSource(path) {
  return readFileSync(join(resources, path), 'utf8');
}

describe('LuCI frontend modules §frontmod', () => {
  it('keeps domain helpers outside the overview composition view', () => {
    assert.match(overview, /require sheepfold\.features\.devices\.types as deviceTypes/);
    assert.match(overview, /require sheepfold\.features\.emergency\.sites as emergencySiteModel/);
    assert.match(overview, /require sheepfold\.features\.devices\.access-lists as deviceAccessLists/);
    assert.match(overview, /require sheepfold\.features\.devices\.editor as deviceEditor/);
    assert.match(overview, /require sheepfold\.features\.devices\.inventory as deviceInventory/);
    assert.match(overview, /require sheepfold\.features\.devices\.table as deviceTableModel/);
    assert.match(overview, /require sheepfold\.features\.devices\.selection as deviceSelection/);
    assert.match(overview, /require sheepfold\.features\.administrators\.model as administratorModel/);
    assert.match(overview, /require sheepfold\.features\.administrators\.view as administratorView/);
    assert.match(overview, /require sheepfold\.features\.administrators\.editor as administratorEditor/);
    assert.match(overview, /require sheepfold\.features\.groups\.model as groupModel/);
    assert.match(overview, /require sheepfold\.features\.groups\.view as groupView/);
    assert.match(overview, /require sheepfold\.features\.groups\.editor as groupEditor/);
    assert.match(overview, /require sheepfold\.features\.integrations\.panel as integrationPanel/);
    assert.match(overview, /require sheepfold\.features\.logs\.panel as logPanelModel/);
    assert.match(overview, /require sheepfold\.features\.messenger\.settings as messengerSettings/);
    assert.match(overview, /require sheepfold\.features\.pairing\.qr as pairingQr/);
    assert.match(overview, /require sheepfold\.features\.router\.info as routerInfo/);
    assert.match(overview, /require sheepfold\.features\.router\.maintenance as routerMaintenance/);
    assert.match(overview, /require sheepfold\.features\.wifi\.payload as wifiPayload/);
    assert.match(overview, /require sheepfold\.features\.wifi\.cards as wifiCards/);
    assert.match(overview, /require sheepfold\.features\.wifi\.editor as wifiEditorModel/);
    assert.match(overview, /require sheepfold\.features\.schedules\.model as scheduleModel/);
    assert.match(overview, /require sheepfold\.features\.schedules\.view as scheduleView/);
    assert.match(overview, /require sheepfold\.features\.schedules\.editor as scheduleEditor/);
    assert.match(overview, /require sheepfold\.features\.settings\.draft as settingsDraftModel/);
    assert.match(overview, /require sheepfold\.features\.settings\.backup as settingsBackupModel/);
    assert.match(overview, /require sheepfold\.features\.settings\.backup-panel as settingsBackupPanelModel/);
    assert.match(overview, /require sheepfold\.features\.settings\.general as settingsGeneralModel/);
    assert.match(overview, /require sheepfold\.features\.settings\.persistence as settingsPersistenceModel/);
    assert.match(overview, /require sheepfold\.features\.sites\.status as siteListStatus/);
    assert.match(overview, /require sheepfold\.features\.storage\.panel as storagePanelModel/);
    assert.match(overview, /require sheepfold\.core\.backend\.router as routerBackend/);
    assert.match(overview, /require sheepfold\.core\.security\.random as secureRandom/);
    assert.match(overview, /require sheepfold\.shared\.forms as sharedForms/);
    assert.match(overview, /require sheepfold\.shared\.icons as sharedIcons/);
    assert.match(overview, /require sheepfold\.shared\.downloads as downloads/);

    assert.doesNotMatch(overview, /function reedSolomonGenerator/);
    assert.doesNotMatch(overview, /function logPhrasePattern/);
    assert.doesNotMatch(overview, /function timeToMinutes/);
    assert.doesNotMatch(overview, /function messengerField/);
    assert.doesNotMatch(overview, /function scheduleWindowsOverlap/);
    assert.doesNotMatch(overview, /function parseDhcpLeases/);
    assert.doesNotMatch(overview, /function parseArpTable/);
    assert.doesNotMatch(overview, /function addRouterDevice/);
    assert.doesNotMatch(overview, /function renderLogRows/);
    assert.doesNotMatch(overview, /function createLogFilterUi/);
    assert.doesNotMatch(overview, /function showEncryptedSettingsExport/);
    assert.doesNotMatch(overview, /function showImportConfirmation/);
    assert.doesNotMatch(overview, /function downloadTextFile/);
    assert.doesNotMatch(overview, /function logStorageLocationField/);
    assert.doesNotMatch(overview, /function yandexDiskMaintenancePanel/);
    assert.doesNotMatch(overview, /function saveWifiNetworksNow/);
    assert.doesNotMatch(overview, /function wifiSaveBar/);
    assert.doesNotMatch(overview, /function siteFilteringIntegrationBox/);
    assert.doesNotMatch(overview, /function routerIpv6Field/);
    assert.doesNotMatch(overview, /function validateSettingsDraft/);
    assert.doesNotMatch(overview, /function saveGlobalOptions/);
    assert.doesNotMatch(overview, /function appPortField/);
    assert.doesNotMatch(overview, /function autoConfigureDevicesField/);
    assert.doesNotMatch(overview, /Math\.random\(\)/);
  });

  it('keeps each helper focused on its own domain', () => {
    const qr = moduleSource('sheepfold/features/pairing/qr.js');
    const types = moduleSource('sheepfold/features/devices/types.js');
    const accessLists = moduleSource('sheepfold/features/devices/access-lists.js');
    const deviceEditor = moduleSource('sheepfold/features/devices/editor.js');
    const inventory = moduleSource('sheepfold/features/devices/inventory.js');
    const logs = moduleSource('sheepfold/features/logs/model.js');
    const logPanel = moduleSource('sheepfold/features/logs/panel.js');
    const random = moduleSource('sheepfold/core/security/random.js');
    const router = moduleSource('sheepfold/core/backend/router.js');
    const routerInfo = moduleSource('sheepfold/features/router/info.js');
    const maintenance = moduleSource('sheepfold/features/router/maintenance.js');
    const wifi = moduleSource('sheepfold/features/wifi/payload.js');
    const forms = moduleSource('sheepfold/shared/forms.js');
    const icons = moduleSource('sheepfold/shared/icons.js');
    const schedules = moduleSource('sheepfold/features/schedules/model.js');
    const groups = moduleSource('sheepfold/features/groups/model.js');
    const administrators = moduleSource('sheepfold/features/administrators/model.js');
    const deviceTable = moduleSource('sheepfold/features/devices/table.js');
    const deviceSelection = moduleSource('sheepfold/features/devices/selection.js');
    const wifiCards = moduleSource('sheepfold/features/wifi/cards.js');
    const wifiEditor = moduleSource('sheepfold/features/wifi/editor.js');
    const messenger = moduleSource('sheepfold/features/messenger/settings.js');
    const settingsDraft = moduleSource('sheepfold/features/settings/draft.js');
    const settingsGeneral = moduleSource('sheepfold/features/settings/general.js');
    const settingsPersistence = moduleSource('sheepfold/features/settings/persistence.js');
    const settingsBackup = moduleSource('sheepfold/features/settings/backup.js');
    const settingsBackupPanel = moduleSource('sheepfold/features/settings/backup-panel.js');
    const downloads = moduleSource('sheepfold/shared/downloads.js');
    const siteListStatus = moduleSource('sheepfold/features/sites/status.js');
    const storagePanel = moduleSource('sheepfold/features/storage/panel.js');
    const emergencySites = moduleSource('sheepfold/features/emergency/sites.js');
    const scheduleView = moduleSource('sheepfold/features/schedules/view.js');
    const scheduleEditor = moduleSource('sheepfold/features/schedules/editor.js');
    const groupView = moduleSource('sheepfold/features/groups/view.js');
    const groupEditor = moduleSource('sheepfold/features/groups/editor.js');
    const integrationPanel = moduleSource('sheepfold/features/integrations/panel.js');
    const administratorView = moduleSource('sheepfold/features/administrators/view.js');
    const administratorEditor = moduleSource('sheepfold/features/administrators/editor.js');

    assert.match(qr, /function createQrMatrix/);
    assert.match(types, /function displayedType/);
    assert.match(types, /function infer/);
    assert.match(types, /byValue: byValue/);
    assert.match(accessLists, /function updatedValues/);
    assert.match(accessLists, /function conflictingList/);
    assert.match(deviceEditor, /function open\(deps, device\)/);
    assert.doesNotMatch(deviceEditor, /uci\.(get|set|unset|remove)|routerControl|saveUciChanges/);
    assert.match(inventory, /function parseDhcp/);
    assert.match(inventory, /function parseArp/);
    assert.match(inventory, /function build\(options\)/);
    assert.match(overview, /function deviceTypeByValue\(value\)[\s\S]*deviceTypes\.byValue\(value\)/);
    assert.match(logs, /function filterView/);
    assert.match(logs, /function maskedExport/);
    assert.match(logPanel, /function renderRows/);
    assert.match(logPanel, /function showExportModal/);
    assert.match(logPanel, /deps\.clear\(\)/);
    assert.match(logPanel, /deps\.download\(/);
    assert.doesNotMatch(logPanel, /\bfs\.|\buci\.|routerBackend|routerControl/);
    assert.match(random, /crypto\.getRandomValues/);
    assert.doesNotMatch(random, /Math\.random/);
    assert.match(router, /function parseKeyValues/);
    assert.match(routerInfo, /function renderContent/);
    assert.match(maintenance, /function updateRow/);
    assert.match(wifi, /function build\(ssid, password, encryption\)/);
    assert.match(forms, /function checkboxControl/);
    assert.match(icons, /function adminCrown/);
    assert.match(schedules, /function windowsOverlap/);
    assert.match(groups, /function nextColor/);
    assert.match(administrators, /function fromSections/);
    assert.match(deviceTable, /function sortHeader/);
    assert.match(deviceSelection, /function create\(options\)/);
    assert.match(wifiCards, /function networkBox/);
    assert.match(wifiEditor, /function savePlan\(editors\)/);
    assert.match(wifiEditor, /function create\(deps\)/);
    assert.match(wifiEditor, /deps\.setOption/);
    assert.match(wifiEditor, /deps\.save\(\)\.then\(deps\.reload\)/);
    assert.doesNotMatch(wifiEditor, /\buci\.(get|set|unset|remove)|\bfs\.|saveUciChanges|overview/);
    assert.match(messenger, /function settingsBox/);
    assert.match(settingsDraft, /function dirtySavers/);
    assert.match(settingsGeneral, /function automaticSetupDraft/);
    assert.match(settingsGeneral, /function render\(deps\)/);
    assert.doesNotMatch(settingsGeneral, /\buci\.|saveUciChanges|routerControl|overview/);
    assert.match(settingsPersistence, /function validateDraft/);
    assert.match(settingsPersistence, /function partitionOptions/);
    assert.match(settingsPersistence, /function stageSection/);
    assert.doesNotMatch(settingsPersistence, /saveUciChanges|routerControl|overview/);
    assert.match(overview, /settingsPersistence\.validate\(options\)/);
    assert.match(overview, /settingsPersistence\.save\(options\)/);
    assert.match(settingsBackup, /function encrypt\(payload, password\)/);
    assert.match(settingsBackup, /function validateAccessLists/);
    assert.match(settingsBackupPanel, /function create\(deps\)/);
    assert.match(settingsBackupPanel, /function showImportConfirmation\(payload\)/);
    assert.match(settingsBackupPanel, /downloads\.textFile/);
    assert.doesNotMatch(settingsBackupPanel, /\buci\.(get|set|unset|remove)|saveUciChanges|routerControl/);
    assert.match(downloads, /function textFile\(filename, text\)/);
    assert.match(siteListStatus, /function describe\(values\)/);
    assert.match(siteListStatus, /site-lists-status/);
    assert.match(siteListStatus, /function sourceRecords\(values\)/);
    assert.match(siteListStatus, /site-lists-accept-shrink/);
    assert.match(siteListStatus, /var remaining = 10/);
    assert.match(storagePanel, /function create\(deps\)/);
    assert.match(storagePanel, /function logStorageLocationField/);
    assert.match(storagePanel, /deps\.routerControl/);
    assert.doesNotMatch(storagePanel, /\buci\.(get|set|unset|remove)|safeUciSections|overview/);
    assert.match(emergencySites, /function normalizeDomain/);
    assert.match(emergencySites, /function stage\(uci, config, sites\)/);
    assert.match(scheduleView, /function render\(deps, embedded\)/);
    assert.match(scheduleEditor, /function open\(deps, section, copyMode\)/);
    assert.doesNotMatch(scheduleEditor, /uci\.(get|set|unset|remove)|safeUciSections|overview/);
    assert.match(groupView, /function render\(deps, embedded\)/);
    assert.match(groupView, /function refresh\(\)/);
    assert.doesNotMatch(groupView, /visual test build/);
    assert.doesNotMatch(groupView, /window\.location\.reload/);
    assert.match(groupEditor, /function openSettings\(deps, groupName, section, onSave\)/);
    assert.match(groupEditor, /function openAdd\(deps, existingNames, onSave\)/);
    assert.doesNotMatch(groupEditor, /uci\.(get|set|unset|remove)|safeUciSections|window\.location\.reload/);
    assert.match(integrationPanel, /function render\(deps\)/);
    assert.match(integrationPanel, /function siteFilteringBox\(deps\)/);
    assert.match(integrationPanel, /function ipv6Draft\(mode, current, source\)/);
    assert.doesNotMatch(integrationPanel, /\buci\.(get|set|unset|remove)|\bfs\.|routerControl|settingsDraft|overview/);
    assert.match(administratorView, /function render\(deps, embedded\)/);
    assert.match(administratorEditor, /function openAdd\(deps, onSave\)/);
    assert.match(administratorEditor, /function openBinding\(deps, admin, onSave\)/);
    assert.match(administratorEditor, /function openSettings\(deps, admin, pairing, callbacks\)/);
    assert.doesNotMatch(administratorEditor, /uci\.(get|set|unset|remove)|routerControl|generatePairingCode/);
  });
});
