/*
 * Каноническая карта связей между путями Sheepfold и соседними контрактами.
 * Правила отделены от CLI и Git, чтобы их можно было проверять обычными unit-тестами
 * и расширять вместе с новой подсистемой без правки исполняющего кода. §impact1
 */

export const riskLevels = Object.freeze(['low', 'medium', 'high', 'critical']);

export const checkCatalog = Object.freeze({
  docs: Object.freeze({
    command: 'npm.cmd run quality:docs',
    automatic: true,
    description: 'Ссылки, §-теги, test/npm-контракты и объективная структура изменённой документации.',
  }),
  lintJs: Object.freeze({
    command: 'npm.cmd run lint:js',
    automatic: true,
    description: 'ESLint для LuCI, Node-инструментов и тестов.',
  }),
  lintAndroid: Object.freeze({
    command: 'npm.cmd run lint:android',
    automatic: true,
    description: 'Android Lint обоих приложений через их Gradle Wrapper.',
  }),
  icons: Object.freeze({
    command: 'npm.cmd run icons:check',
    automatic: true,
    description: 'Синхронизация единого каталога значков с LuCI и Android-ресурсами.',
  }),
  androidBuild: Object.freeze({
    command: 'android\\gradlew.bat -p android :app:assembleDebug; android-child\\gradlew.bat -p android-child :app:assembleDebug',
    automatic: false,
    description: 'Сборка затронутого Android-приложения после Kotlin/XML-правок.',
  }),
  routerFrontend: Object.freeze({
    command: 'npm.cmd run router:frontend',
    automatic: false,
    description: 'Read-only проверка настоящего LuCI на desktop и mobile.',
  }),
  routerReadOnly: Object.freeze({
    command: 'npm.cmd run router:readOnly',
    automatic: false,
    description: 'Read-only проверка backend и состояния тестового роутера.',
  }),
  routerFullSafe: Object.freeze({
    command: 'npm.cmd run router:fullSafe',
    automatic: false,
    description: 'Backup, безопасные изменения и восстановление тестового роутера.',
  }),
  routerRuntimeMatrix: Object.freeze({
    command: 'npm.cmd run router:runtimeMatrix',
    automatic: false,
    description: 'Живая матрица текущих access, DNS и интеграционных режимов.',
  }),
  githubPackages: Object.freeze({
    command: 'gh workflow run "Build OpenWrt packages"',
    automatic: false,
    description: 'Настоящая сборка IPK и OpenWrt APK в официальном SDK.',
  }),
  nativeRelay: Object.freeze({
    command: 'sh tools/messageRelay/runNativeCryptoTests.sh --sanitize',
    automatic: false,
    description: 'Linux-only native SFMR1 gate с OpenSSL/Jansson; затем отдельно target SDK и vector на OpenWrt.',
  }),
});

export const impactRules = Object.freeze([
  Object.freeze({
    id: 'remoteSupportProtocol',
    area: 'Экспериментальный public/private support contract',
    pattern: /^(?:tools\/remoteSupport\/|tests\/remoteSupportTransport)/,
    categories: ['security', 'tooling'],
    checks: ['docs', 'lintJs'],
    risk: 'critical',
    review: 'Сверить private vendor pin, CSR/CA/SPKI, RAM-only replay и неизменяемые сроки; Node contract не доказывает SSH или router runtime.',
    full: true,
  }),
  Object.freeze({
    id: 'nativeRelay',
    area: 'Native SFMR1 crypto boundary',
    pattern: /^(?:package\/sheepfold-message-relay-crypto\/|tools\/messageRelay\/(?:.*\.mjs|.*\.sh)|tests\/fixtures\/family-message-relay\/)/,
    categories: ['backendFast', 'packaging', 'security'],
    checks: ['docs', 'nativeRelay'],
    risk: 'critical',
    review: 'Проверить strict JSON, размеры, GCM tag, byte-exact vector и отсутствие runtime/enrollment до gates; native test не заменяет ABI build.',
    full: true,
  }),
  Object.freeze({
    id: 'aiServerCoreExperiment',
    area: 'Экспериментальное серверное ядро ИИ',
    pattern: /^experimental\/(?:README\.ru\.md$|ai-server-core\/)/,
    categories: ['ai', 'security'],
    checks: ['docs'],
    risk: 'high',
    review: 'Проверить fail-closed ворота, приватность, tenant-разделение, строгие схемы и отсутствие связи с поставкой IPK/APK.',
  }),
  Object.freeze({
    id: 'projectIcons',
    area: 'Единый каталог значков',
    pattern: /(?:^icons\/|^scripts\/generateIconCatalog\.mjs$|\/sheepfold\/shared\/icon-registry\.js$|\/sheepfold\/shared\/icons\.js$|^docs\/icon-catalog\.ru\.md$|0017-central-project-icon-catalog)/,
    categories: ['android', 'luci', 'tooling'],
    checks: ['icons'],
    risk: 'medium',
    review: 'Проверить места использования, толщину paths/thinPaths и визуально открыть icons/catalog.html.',
  }),
  Object.freeze({
    id: 'localization',
    area: 'Локализация интерфейса',
    pattern: /(?:^po\/[^/]+\/[^/]+\.po$|^package\/luci-app-[^/]+\/po\/(?:[^/]+\/[^/]+\.po|templates\/[^/]+\.pot)$|\/sheepfold\/i18n\/[^/]+\.json$)/,
    categories: ['luci', 'packaging'],
    checks: ['routerFrontend', 'githubPackages'],
    risk: 'medium',
    review: 'Проверить точный регистр msgid, переводы RU/ZH и синхронизацию PO, JSON и пакетного LMO.',
  }),
  Object.freeze({
    id: 'luciFrontend',
    area: 'LuCI frontend',
    pattern: /package\/luci-app-[^/]+\/htdocs\/luci-static\/resources\//,
    categories: ['luci'],
    checks: ['lintJs', 'routerFrontend'],
    risk: 'medium',
    review: 'Проверить локализацию, mobile overflow, состояния загрузки/ошибки и версию JS/CSS.',
  }),
  Object.freeze({
    id: 'devicePresentation',
    area: 'Таблица устройств в LuCI',
    pattern: /features\/devices\/(?:table\.js|responsive\.css)$/,
    categories: ['luci'],
    checks: ['lintJs', 'routerFrontend'],
    risk: 'medium',
    review: 'Проверить desktop/mobile раскладку, сортировку, фильтр и доступность всех действий.',
  }),
  Object.freeze({
    id: 'devicePassport',
    area: 'Устройства и их паспорт',
    pattern: /(?:features\/devices\/(?!(?:table\.js|responsive\.css)$)|(?:^|\/)sheepfold-device-|(?:^|\/)device-(?:mdns|ssdp|ws-discovery)(?:[./-]|$)|^docs\/device-(?:passport|detection)\.ru\.md$)/,
    categories: ['devices', 'access', 'security'],
    checks: ['routerReadOnly'],
    risk: 'high',
    review: 'Не смешать MAC-карточку, классификацию, trusted baseline и права родителя.',
  }),
  Object.freeze({
    id: 'userManagement',
    area: 'Группы, расписания и администраторы',
    pattern: /(?:features\/(?:groups|schedules|administrators)\/|sheepfold-(?:schedule|group|admin|pair))/,
    categories: ['luci', 'access', 'security'],
    checks: ['routerReadOnly'],
    risk: 'high',
    review: 'Проверить конфликт расписаний, protected groups и границу административного сопряжения.',
  }),
  Object.freeze({
    id: 'countryProfiles',
    area: 'Профили стран',
    pattern: /root\/usr\/share\/sheepfold\/country-profiles\/[^/]+\.json$/,
    categories: ['backendFast', 'packaging', 'sites'],
    checks: ['routerReadOnly'],
    risk: 'high',
    review: 'Проверить JSON-схему, аварийно-полезные сайты, NTP-рекомендации и безопасную миграцию выбранного профиля.',
  }),
  Object.freeze({
    id: 'routerBackend',
    area: 'Router backend',
    pattern: /package\/luci-app-[^/]+\/root\/(?:usr\/libexec\/sheepfold|www\/cgi-bin)\//,
    categories: ['backendFast'],
    checks: ['routerReadOnly'],
    risk: 'high',
    review: 'Проверить BusyBox-совместимость, validation, lock, exit code и структурированный JSON.',
  }),
  Object.freeze({
    id: 'routerService',
    area: 'Служба OpenWrt',
    pattern: /^package\/luci-app-[^/]+\/root\/etc\/init\.d\/sheepfold$/,
    categories: ['backendFast', 'packaging', 'security'],
    checks: ['routerReadOnly', 'routerFullSafe'],
    risk: 'critical',
    review: 'Проверить procd lifecycle, порядок запуска, права процесса и восстановление после reboot.',
    full: true,
  }),
  Object.freeze({
    id: 'rpcAcl',
    area: 'LuCI rpcd ACL',
    pattern: /package\/luci-app-[^/]+\/root\/usr\/share\/rpcd\/acl\.d\/[^/]+\.json$/,
    categories: ['backendFast', 'luci', 'security'],
    checks: ['routerReadOnly', 'routerFrontend'],
    risk: 'critical',
    review: 'Сверить минимальные rpcd-права с фактическими LuCI-вызовами и не расширять exec/UCI-доступ ради одного экрана.',
    full: true,
  }),
  Object.freeze({
    id: 'sharedApi',
    area: 'Общий API-контракт',
    pattern: /(?:sheepfold-api|android-openwrt-api|RouterAdminClient|ClientStatusRepository|SecureRouterConnectionManager)/,
    categories: ['backendFast', 'android', 'security'],
    checks: ['lintAndroid', 'androidBuild', 'routerReadOnly'],
    risk: 'critical',
    review: 'Сверить HTTP status, stable errorCode, старого клиента, auth и неоднозначный повтор команды.',
    full: true,
  }),
  Object.freeze({
    id: 'homeNetworkAccess',
    area: 'Доверенная домашняя сеть родительского APK',
    pattern: /(?:sheepfold-home-(?:network|firewall)|settings\/home-network\.js$|HomeRouterEndpoints\.kt$|RouterEndpointRecovery\.kt$|SheepfoldConnectionStore\.kt$)/,
    categories: ['android', 'backendFast', 'luci', 'networkIntegration', 'security'],
    checks: ['docs', 'lintAndroid', 'routerReadOnly', 'routerFullSafe'],
    risk: 'critical',
    review: 'Проверить явное согласие на upstream, root API без LuCI, source/MAC/TLS и отсутствие повторной записи при смене адреса; живой переход Wi-Fi описан в home-network-access.ru.md.',
    full: true,
  }),
  Object.freeze({
    id: 'uciMigration',
    area: 'UCI и миграция',
    pattern: /(?:sheepfold\.uci\.defaults|etc\/uci-defaults|postinst|preinst|uci-config-migration|settings\/save)/,
    categories: ['backendFast', 'packaging', 'security'],
    checks: ['routerFullSafe'],
    risk: 'critical',
    review: 'Проверить первую установку, upgrade живого конфига, named sections, secrets и повторный запуск.',
    full: true,
  }),
  Object.freeze({
    id: 'networkPolicy',
    area: 'Firewall, DNS и списки сайтов',
    pattern: /(?:firewall|nft|domain-policy|site-list|adguard|dnsmasq|emergency-site)/,
    categories: ['access', 'sites', 'security', 'networkIntegration'],
    checks: ['routerFullSafe', 'routerRuntimeMatrix'],
    risk: 'critical',
    review: 'Проверить приоритет устройств, последний рабочий cache, транзакционный rollback и чужие объекты интеграций.',
    full: true,
  }),
  Object.freeze({
    id: 'androidApps',
    area: 'Android parent/child',
    pattern: /^(?:android|android-child)\//,
    categories: ['android', 'security'],
    checks: ['lintAndroid', 'androidBuild'],
    risk: 'high',
    review: 'Проверить оба APK, lifecycle, offline/timeout и сохранение локальной защиты приложения.',
  }),
  Object.freeze({
    id: 'packageReleaseMetadata',
    area: 'Версия OpenWrt-пакета',
    pattern: /^package\/[^/]+\/Makefile$/,
    kinds: ['packageReleaseOnly'],
    categories: ['packaging', 'tooling'],
    checks: ['githubPackages'],
    risk: 'critical',
    review: 'Проверить имя пакета, cache-busting и SDK-сборку обоих вариантов.',
    full: true,
  }),
  Object.freeze({
    id: 'packaging',
    area: 'Пакет, release и updater',
    pattern: /(?:^package\/[^/]+\/Makefile$|^scripts\/(?:build-test-ipk|sheepfold_variants|prepare-openwrt|collect-openwrt|create-openwrt-release)|(?:^|\/)sheepfold-updater$|^install\.sh$|^uninstall\.sh$|^\.github\/workflows\/)/,
    excludeKinds: ['packageReleaseOnly'],
    categories: ['packaging', 'tooling', 'security'],
    checks: ['githubPackages'],
    risk: 'critical',
    review: 'Проверить Standard/AI, IPK/OpenWrt APK, package identity, upgrade и сохранение UCI.',
    full: true,
  }),
  Object.freeze({
    id: 'adminConfigRuntimeTestFixture',
    area: 'Общий admin-config runtime-fixture тестов',
    pattern: /^tests\/helpers\/adminConfigRuntimeFixture\.mjs$/,
    categories: ['tooling'],
    checks: ['lintJs'],
    risk: 'medium',
    directTests: Object.freeze([
      'adminConfigBoundaryRuntime.test.mjs',
      'adminRollbackRecoveryRuntime.test.mjs',
      'adminTransactionPendingRuntime.test.mjs',
      'adminTransactionPreparationRuntime.test.mjs',
      'adminWifiValidationRuntime.test.mjs',
    ]),
    review: 'Запустить всех прямых потребителей изменённого fixture; длинный runtime-файл не переносить ради этого в быструю tooling-категорию.',
  }),
  Object.freeze({
    id: 'apiRateLimitRuntimeTestFixture',
    area: 'Общий rate-limit runtime-fixture тестов',
    pattern: /^tests\/helpers\/apiRateLimitFixture\.mjs$/,
    categories: ['tooling'],
    checks: ['lintJs'],
    risk: 'medium',
    directTests: Object.freeze(['apiRateLimitRuntime.test.mjs']),
    review: 'Запустить прямой rate-limit runtime-тест, не расширяя tooling-категорию соседними backend-стендами.',
  }),
	Object.freeze({
		id: 'architectureDocs',
		area: 'Архитектура и правила агентов',
		pattern: /(?:^(?:README(?:\.ru)?|AGENTS|CODING_RULES)\.md$|^\.agents\/skills\/|^(?:docs|utilities)\/)/,
    categories: ['tooling'],
    checks: ['docs'],
    risk: 'low',
    review: 'Сверить ADR, профильный документ, §-теги и автоматическую проверку контракта.',
  }),
  Object.freeze({
    id: 'testTooling',
    area: 'Тестовый инструментарий',
    pattern: /^(?:\.git(?:ignore|attributes)$|package\.json$|eslint\.config\.js$|tests\/|tools\/|scripts\/)/,
    categories: ['tooling'],
    checks: ['lintJs'],
    risk: 'medium',
    review: 'Проверить purpose note, изменяемое состояние, границу доказательства и запуск в Windows/CI.',
  }),
]);
